version: 2.1

orbs:
  zulip: ponylang/zulip@1

jobs:
  release-vs-ponyc-release-openssl-098:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=release ssl=0.9.0
      - zulip/status:
          fail_only: true

  debug-vs-ponyc-release-openssl-098:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=debug ssl=0.9.0
      - zulip/status:
          fail_only: true

  release-vs-ponyc-master-openssl-098:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=release ssl=0.9.0
      - zulip/status:
          fail_only: true

  debug-vs-ponyc-master-openssl-098:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=debug ssl=0.9.0
      - zulip/status:
          fail_only: true

  release-vs-ponyc-release-openssl-110:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-1.1.0.bash
      - run: make test config=release ssl=1.1.x
      - zulip/status:
          fail_only: true

  debug-vs-ponyc-release-openssl-110:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-1.1.0.bash
      - run: make test config=debug ssl=1.1.x
      - zulip/status:
          fail_only: true

  release-vs-ponyc-master-openssl-110:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-1.1.0.bash
      - run: make test config=release ssl=1.1.x
      - zulip/status:
          fail_only: true

  debug-vs-ponyc-master-openssl-110:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-1.1.0.bash
      - run: make test config=debug ssl=1.1.x
      - zulip/status:
          fail_only: true

workflows:
  version: 2.1
  commit:
    jobs:
      - release-vs-ponyc-release-openssl-098:
          context: org-global
      - debug-vs-ponyc-release-openssl-098:
          context: org-global
      - release-vs-ponyc-release-openssl-110:
          context: org-global
      - debug-vs-ponyc-release-openssl-110:
          context: org-global

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - release-vs-ponyc-master-openssl-098:
          context: org-global
      - debug-vs-ponyc-master-openssl-098:
          context: org-global
      - release-vs-ponyc-master-openssl-110:
          context: org-global
      - debug-vs-ponyc-master-openssl-110:
          context: org-global

